apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orthanc-oauth.fullname" . }}
  labels:
    {{- include "orthanc-oauth.labels" . | nindent 4 }}
type: Opaque
data:
  oauth-client-secret: {{ .Values.oauth.clientSecret | b64enc | quote }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ .Values.redis.password | default "" | b64enc | quote }}
  {{- end }}
